name: Bug report
description: File a bug report.
title: '[Bug]: '
labels: ['bug 🐛']
assignees: 'falsepopsky'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug. Before proceeding, please ensure that you have tested the issue with the latest version.
  - type: input
    attributes:
      label: Package version
      description: 'Which version are you using?'
      placeholder: e.g. v0.0.6
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: 'Clearly describe the issue you encountered, providing as much detail as possible.'
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction/example
      description: |
        Please provide a link to a GitHub repository that contains a minimal reproduction of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: 'Describe the general steps to reproduce the error or problem. Include any necessary context or prerequisites.'
    validations:
      required: true
