name: Question ❓
description: Usage question or discussion about the package.
title: '[Question]: '
labels: ['question ❓']
assignees: 'falsepopsky'

body:
  - type: markdown
    attributes:
      value: |
        Please note that this issue tracker is specifically for questions and discussions related to the package itself. If you have questions about the underlying API or services beyond our control, we recommend reaching out to the appropriate support channels for those services.
        When asking your question, please provide as much relevant detail as possible to help us understand and assist you better. We appreciate your engagement and look forward to addressing your question!.
  - type: textarea
    id: question-summary
    attributes:
      label: Question for @untidy/thetvdb
      description: 'Let us know how we can assist you!'
    validations:
      required: true
